AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cf-sam-openapi-apigw
Globals:
  Function:
    Timeout: 20
    MemorySize: 128

Resources:
  AnimalsApi:
    !Include ./resources/apigw/animalsApiGw.yaml
  AnimalsDdbTable:
    !Include ./resources/dynamodb/animalsTable.yaml
  GetAnimalByIdLambda:
    !Include ./resources/lambda/getAnimalByIdLambda.yaml
  GetAnimalByIdLambdaRole:
    !Include ./resources/lambda/getAnimalByIdLambdaRole.yaml

Outputs:
  GetAnimalByIdLambda:
    Value: !GetAtt GetAnimalByIdLambda.Arn
  GetAnimalByIdLambdaRole:
    Value: !GetAtt GetAnimalByIdLambdaRole.Arn